#!/bin/bash

USERNAME=CanICodeDis
echo "Gib die Commit-message ein:"
read -p 'Message: ' commitMsg
git add *
git commit -a -m "$commitMsg"
echo "Wohin pushen?"
read -p 'Ziel: ' zielRepo
git push -u $zielRepo
